/**:
  ros__parameters:
    # Used when odrive has no torque constant set
    torque_multiplier: 1.0

    agent_name: furuta_pendulum_full_pretrained_high_variance.pt

    # High variance:
    dtheta0_alpha: 1.0
    dtheta1_alpha: 1.0
    action_alpha: 0.1
    # Also works for action_alpha 0.2 and 0.3

    # SDE:
    # dtheta0_alpha: 0.25
    # dtheta1_alpha: 0.25
    # action_alpha: 1.0