version: "0.2"
ignorePaths: []
words:
  - Acompare
  - ADCG
  - ALLC
  - assigndata
  - BLASFEO
  - bringup
  - codegen
  - coinor
  - colcon
  - copydata
  - CPPADCG
  - cpptools
  - ctdsl
  - ctransform
  - cyclonedds
  - DCMAKE
  - DDPG
  - ddtheta
  - descritpion
  - devcontainer
  - DIKFAST
  - discretization
  - dtdsl
  - dtheta
  - dtype
  - dynparams
  - eamodio
  - Eigen
  - EULERCT
  - Feath
  - Featherstone's
  - feedforward
  - fext
  - FURUTAPENDULUM
  - gazebosim
  - GLEW
  - GNMS
  - GNRICCATI
  - Hardtanh
  - HPIPM
  - iitrbd
  - ilqr
  - imageio
  - initialpose
  - interm
  - Jacobians
  - JSIM
  - JSIMC
  - kindsl
  - libboost
  - LIBDIR
  - libeigen
  - libipopt
  - liblapack
  - libomp
  - libtorch
  - linearization
  - Linearizer
  - linearizes
  - Linv
  - locp
  - maciej
  - matplotlib
  - mavx
  - Meshcat
  - mfma
  - mtune
  - mujoco
  - multibody
  - NJOINTS
  - NLOC
  - nlocp
  - NSTATE
  - numpy
  - onnx
  - Onnxable
  - onnxed
  - opset
  - optcon
  - Precomputes
  - pylance
  - Qcompare
  - qpos
  - quadrotor
  - qvel
  - randn
  - rclcpp
  - ROBCOGEN
  - ROBOGEN
  - rosdep
  - rosgraph
  - rosrun
  - rviz
  - SDFAST
  - smilerobotics
  - Struct
  - tensorboard
  - timesteps
  - trackbodyid
  - traj
  - twxs
  - urdf
  - vcross
  - Visualizerd
  - Wfatal
  - xacro
  - xftemp
ignoreWords: []
import: []
