/**:
  ros__parameters:
    K: [-3.19943e-17, 19.1822, -1.0, 4.35556]

    # absolute maximum command value that is used in swing up
    u_max: 3.0

    # 0.0 angle - upward position. When absolut angle is less than this threshold
    # transition from swing up to LQR
    lqr_transition_angle: 0.7
