/**:
  ros__parameters:
    K: [-2.92203e-17, 18.931, -0.980082, 4.26494]

    # absolute maximum command value that is used in swing up
    u_max: 3.0

    # 0.0 angle - upward position. When absolut angle is less than this threshold
    # transition from swing up to LQR
    lqr_transition_angle: 0.7
