/**:
  ros__parameters:
    # 150Hz, 0.00028 damping
    # K: [-3.07207e-18, 0.507656, -0.0172039, 0.0474458]
    # 175Hz, 0.0001 damping
    # K: [-3.76757e-18, 0.545336, -0.020137, 0.0563273]
    # 175Hz, 0.00028 damping
    K: [-1.97188e-18, 0.590181, -0.0201872, 0.0556876]

    alpha: 0.95
    # absolute maximum command value that is used in swing up
    u_max: 0.1
    # 0.0 angle - upward position. When absolute angle is less than this threshold
    # transition from swing up to LQR
    lqr_transition_angle: 0.5
    torque_multiplier: 1.7
