/**:
  ros__parameters:
    K: [-3.07207e-18, 0.507656, -0.0172039, 0.0474458]
    alpha: 1.0
    # absolute maximum command value that is used in swing up
    u_max: 0.06
    # 0.0 angle - upward position. When absolute angle is less than this threshold
    # transition from swing up to LQR
    lqr_transition_angle: 0.3
