
/**:
  ros__parameters:
    # parameters from https://www.hindawi.com/journals/jcse/2011/528341/
    m1: 0.3
    m2: 0.075
    
    l1: 0.15
    l2: 0.148
    
    L1: 0.278
    L2: 0.3
    
    J1: 0.0248
    J2: 0.00386
    
    b1: 0.0001
    b2: 0.00028
    
    L: 0.005
    R: 7.8
    Km: 0.09