/**:
  ros__parameters:
    simulation_dt: 0.006666667
    max_torque: 20.0
    max_velocity: 20.0

    initial_conditions:
      theta1: 0.0
      theta2: 0.0

      dtheta1: 0.0
      dtheta2: 0.0

      tau1: 0.0
      tau2: 0.0
