/**:
  ros__parameters:
    K: [2.392972679139878e-13, 27.67743472906659, -1.0001000050001494, 2.7642140972163816]
    
    # absolute maximum command value that is used in swing up
    u_max: 0.5
    
    # 0.0 angle - upward position. When absolute angle is less than this threshold
    # transition from swing up to LQR
    lqr_transition_angle: 0.7