/**:
  ros__parameters:
    K: [-3.117213617190637e-15, 19.26952361008958, -1.000100004999993, 4.352080693946377]
    
    # absolute maximum command value that is used in swing up
    u_max: 10.0
    
    # 0.0 angle - upward position. When absolut angle is less than this threshold
    # transition from swing up to LQR
    lqr_transition_angle: 0.7