/**:
  ros__parameters:
    K: [-3.496073918705701e-14, 55.63173049221518, -3.1623776617494848, 12.6236765162502]
    
    # absolute maximum command value that is used in swing up
    u_max: 10.0
    
    # 0.0 angle - upward position. When absolut angle is less than this threshold
    # transition from swing up to LQR
    lqr_transition_angle: 0.7